version: 2
jobs:
  build:
    machine: true

    working_directory: ~/dockerised-bot

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true # default - false

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar

      - run:
         name: Build Docker image
         command: docker build --cache-from=app -t raniazy/dockerized-bot:$CIRCLE_SHA1 .

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar

      - run:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker push raniazy/dockerized-bot:$CIRCLE_SHA1

      - run:
          name: Deploy to Heroku
          command: |
             docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
             docker tag raniazy/dockerized-bot:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
             docker push registry.heroku.com/$HEROKU_APP_NAME/web

workflows:
  version: 2
  jobs:
      - build
